### ISSUE TITLE
gradient issue

### ISSUE THREAD

**Issue by blueardour** [vinsis/ternary-quantization#1]
HI, @vinsis  Thanks for the pytorch implementation of the TTN.
I have an issue about the code. In quantionization.py line14:

should ` full_precision_grad = a * full_precision_data * w_p_data + b * full_precision_data * w_n_data + c * full_precision_data * 1` be

` full_precision_grad = a * grad_data* w_p_data + b * grad_data* w_n_data + c * grad_data* 1`?

It seems the original gradient not used if employing full_precision_data .

**Comment by vinsis** [comment]
Thanks for pointing out @blueardour. Good catch! I fixed the issue and found that the model training is much more stable now. I was able to get an accuracy of 98.5% on quantized model. 

I have added the updated code, logs and weight to the repo.
