### ISSUE TITLE
Have you tried on other dataset or network?

### ISSUE THREAD

**Issue by blueardour** [vinsis/ternary-quantization#2]
hi, @vinsis 

I wonder if you have tried on other datasets or networks? For example, 
the listed case in https://github.com/czhu95/ternarynet (which seems to be the repo by the paper author). 

I spent many time and couldn't recover the reported accuracy in the paper.

**Comment by vinsis** [comment]
No, I haven't had the time to do so. 

> I spent many time and couldn't recover the reported accuracy in the paper.

Unfortunately that's more common than one might think. What datasets did you try on?

**Comment by blueardour** [comment]
reset20 on cifar10. It seemed the train very unstable even though Adam and small lr were used.

**Comment by vinsis** [comment]
I might try it some time but not anytime soon. Please let me know if you can get it to work.

On a different note I don't have much confidence in practical applicability of this method. Even if most of the layers in your model are quantized, I don't think you can embed the model efficiently on an Android/iOS device non-trivially. At least I haven't seen it happen so far.
