### ISSUE TITLE
ValueError: can’t optimize a non-leaf Tensor?

### ISSUE THREAD

**Issue by yananliusdu** [vinsis/ternary-quantization#4]
change {scaling_factors = [torch.ones(2, requires_grad=True).to(device) for _ in range(len(weights_to_be_quantized))]}

to

 {scaling_factors = [torch.ones(2, requires_grad=True, device=device) for _ in range(len(weights_to_be_quantized))]} 

works

**Comment by vinsis** [comment]
Thank you! Which version of PyTorch are you using?

**Comment by yananliusdu** [comment]
1.1.0
