### ISSUE TITLE
why not ternery weights?

### ISSUE THREAD

**Issue by yananliusdu** [vinsis/ternary-quantization#5]
Hello, I managed to perform your quantized neural network in my machine. however, the trained weights are like this (a kernel): 
     [[[ 0.0000,  0.0000,  0.4256],
          [ 0.0000,  0.4256, -1.4813],
          [ 0.0000,  0.0000,  0.0000]]],
all the weights I got is like this. It seems like not a ternary weights which should be [-A, 0 , A], is it and why?

cheers.

**Comment by vinsis** [comment]
Hi, that is expected. The original paper says:

> ... and quantize the weights to {−Wnl, 0,+Wpl} instead of traditional {-1, 0, +1} or {-E, 0, +E} ...
